### ISSUE TITLE
Should we connect to pinning node in iframe or 3box.js?

### ISSUE THREAD

**Issue by zachferland** [3box/3box-js-iframe#2]
Should we connect to known ipfs nodes here or wait for 3box.js to request to connect to known ipfs node as it does right now. Which is faster?

**Comment by oed** [comment]
I'd say no. In the future we might want to have different clients connect to different nodes.

**Comment by oed** [comment]
Also, connecting within the iframe would break things for people who provide their own ipfs object.

**Comment by zachferland** [comment]
You are saying no to using static config in iframe right? The idea right now to cover all use cases is  to allow a dev to bring their own ipfs obj, and in that case it doesn't use the iframe anyways. 

Also worded this story so poorly, barely remember what i was thinking hah. But i think this is just whether to optimistically load with default configs, which is a lot faster. If we allowed ipfs configs to be pased to iframe, we couldn't load on page load and would have to wait for dev to call func with configs. Which at that speed you should just pass your own ipfs obj and not use the iframe. 

I think the in between solution, would be optimistically load on page load and then have a func for adding pinning nodes (but not passing an entire ipfs config object, since pinning nodes can be connected to after start and loaded)

This is not a blocker for release though, so could be in another sprint.

**Comment by oed** [comment]
> I think the in between solution, would be optimistically load on page load and then have a func for adding pinning nodes (but not passing an entire ipfs config object, since pinning nodes can be connected to after start and loaded)

Isn't that what we are doing now? And also what I suggest we continue doing?

**Comment by zachferland** [comment]
yeah we connect this way, but we don't have a easy/documented func for devs to connect to another pinning node

**Comment by oed** [comment]
Oh, I see. Is it worth creating a wrapper around the ipfs function or should we just document how to access the ipfs object?
If wrapper we should write a story for it.

**Comment by zachferland** [comment]
Resolving with https://github.com/3box/3box-js/pull/239

**Comment by zachferland** [comment]
Iframe doesn't connect to any nodes onload, could also connect to known pinning node on load. Can't remember if there was any reason that i did not do this initially.

**Comment by zachferland** [comment]
Oh reading thread again, see that was the original question, but coming back to, don't see much downside to optimistically connect to default/known node and then client can't connect to others if they want to. Maybe I was thinking either/or before instead of doing both. Both makes sense to me

**Comment by oed** [comment]
That makes sense @zachferland. Do you mind creating a story for it and then closing this?

**Comment by zachferland** [comment]
Closed by https://github.com/3box/3box-js-iframe/issues/5
